export const GAME_LIST_REQUEST = 'GAME_LIST_REQUEST';
export const GAME_LIST_SUCCESS = 'GAME_LIST_SUCCESS';
export const GAME_LIST_FAIL = 'GAME_LIST_FAIL';

export const SINGLE_GAME_REQUEST = 'SINGLE_GAME_REQUEST';
export const SINGLE_GAME_SUCCESS = 'SINGLE_GAME_SUCCESS';
export const SINGLE_GAME_FAIL = 'SINGLE_GAME_FAIL';
